### ISSUE TITLE
Search should display text around first found keyword

### ISSUE THREAD

**Issue by wzrdtales** [gilbitron/Raneto-Core#6]
The current behavior is that the search only displays the page, but always start from the beginning of this page, which first 400 characters may not contain the searched keyword instead this should start at the first keyword, or at the start of the sentence of the first keyword.

**Comment by ryanlelek** [comment]
I agree. What do you think is the easiest way to add this feature fix without searching for the strings ourselves?

**Comment by wzrdtales** [comment]
Had just a quick look at lunr, seems like a contribution to either lunr is needed or something else for the search is considered. Can't say anything about lunr myself, haven't used it yet and did not tested it, would be interesting how good it is performing in high load scenarios.

However, currently either searching directly e.g. with indexOf, using another search lib or contributing to lunr are the options. Probably the latter one could be the preferred option.

**Comment by ryanlelek** [comment]
Closing for repo move.
You may resubmit on the main repo

Please visit us at the [Main Raneto Repo](https://github.com/gilbitron/Raneto)
